---
title: Alight  Marketo Templates
timezone: UTC
collections:
  landing_pages:
    title: Landing Pages
    output: true
    permalink: "/landing-pages/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
