---
title: Alight  Marketo Templates
timezone: UTC
collections:
  landing-pages:
    title: Landing Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
